# Generated by Django 4.2.6 on 2024-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('loan_offer', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
